<rss>
    <channel>
        <item>
            <imag img="https://files.elnashra.com/elnashrafan/pictures/7287731_1463418489.jpg"/>

            <title>حاسس</title>
            <enclosure url="http://ms16.sm3na.com/303/Sm3na_com_47464.mp3"/>
        </item>
        <item>
            <imag img="https://files.elnashra.com/elnashrafan/pictures/7287731_1463418489.jpg"/>

            <title>اذا مش انت	</title>
            <enclosure url="http://ms16.sm3na.com/303/Sm3na_com_47465.mp3"/>
        </item>
        <item>
            <imag img="https://files.elnashra.com/elnashrafan/pictures/7287731_1463418489.jpg"/>

            <title>ما بقاش يسأل عني	</title>
            <enclosure url="http://ms16.sm3na.com/303/Sm3na_com_47466.mp3"/>
        </item>
        <item>
            <imag img="https://files.elnashra.com/elnashrafan/pictures/7287731_1463418489.jpg"/>

            <title>مين</title>
            <enclosure url="http://ms16.sm3na.com/303/Sm3na_com_47467.mp3"/>
        </item>
        <item>
            <imag img="https://files.elnashra.com/elnashrafan/pictures/7287731_1463418489.jpg"/>

            <title>مش مستاهلة	</title>
            <enclosure url="http://ms16.sm3na.com/303/Sm3na_com_47468.mp3"/>
        </item>
        <item>
            <imag img="https://files.elnashra.com/elnashrafan/pictures/7287731_1463418489.jpg"/>

            <title>غريبة</title>
            <enclosure url="http://ms16.sm3na.com/303/Sm3na_com_47469.mp3"/>
        </item>
        <item>
            <imag img="https://files.elnashra.com/elnashrafan/pictures/7287731_1463418489.jpg"/>

            <title>بحر هموم	</title>
            <enclosure url="http://ms16.sm3na.com/303/Sm3na_com_47470.mp3"/>
        </item>
        <item>
            <imag img="https://files.elnashra.com/elnashrafan/pictures/7287731_1463418489.jpg"/>

            <title>معذبني الهوى	</title>
            <enclosure url="http://ms16.sm3na.com/303/Sm3na_com_47471.mp3"/>
        </item>
        <item>
            <imag img="https://files.elnashra.com/elnashrafan/pictures/7287731_1463418489.jpg"/>

            <title>خلوني معو	</title>
            <enclosure url="http://ms16.sm3na.com/303/Sm3na_com_47472.mp3"/>
        </item>
        <item>
            <imag img="https://files.elnashra.com/elnashrafan/pictures/7287731_1463418489.jpg"/>

            <title>يا حبيبي علامك	</title>
            <enclosure url="http://ms4.sm3na.com/303/Sm3na_com_32444.mp3"/>
        </item>
        <item>
            <imag img="https://files.elnashra.com/elnashrafan/pictures/7287731_1463418489.jpg"/>

            <title>ما عاد فيني روح	</title>
            <enclosure url="http://ms4.sm3na.com/303/Sm3na_com_32438.mp3"/>
        </item>
        <item>
            <imag img="https://files.elnashra.com/elnashrafan/pictures/7287731_1463418489.jpg"/>

            <title>ماروم</title>
            <enclosure url="http://ms4.sm3na.com/303/Sm3na_com_32439.mp3"/>
        </item>
        <item>
            <imag img="https://files.elnashra.com/elnashrafan/pictures/7287731_1463418489.jpg"/>

            <title>مين هي	</title>
            <enclosure url="http://ms4.sm3na.com/303/Sm3na_com_32440.mp3"/>
        </item>
        <item>
            <imag img="https://files.elnashra.com/elnashrafan/pictures/7287731_1463418489.jpg"/>

            <title>ناسيك</title>
            <enclosure url="http://ms4.sm3na.com/303/Sm3na_com_32441.mp3"/>
        </item>
        <item>
            <imag img="https://files.elnashra.com/elnashrafan/pictures/7287731_1463418489.jpg"/>

            <title>نظر عيني	</title>
            <enclosure url="http://ms4.sm3na.com/303/Sm3na_com_32442.mp3"/>
        </item>
        <item>
            <imag img="https://files.elnashra.com/elnashrafan/pictures/7287731_1463418489.jpg"/>

            <title>نلوم الوقت	</title>
            <enclosure url="http://ms4.sm3na.com/303/Sm3na_com_32443.mp3"/>
        </item>
        <item>
            <imag img="https://files.elnashra.com/elnashrafan/pictures/7287731_1463418489.jpg"/>

            <title>سلمولي	</title>
            <enclosure url="http://ms4.sm3na.com/303/Sm3na_com_32436.mp3"/>
        </item>
        <item>
            <imag img="https://files.elnashra.com/elnashrafan/pictures/7287731_1463418489.jpg"/>

            <title>صدفة	</title>
            <enclosure url="http://ms4.sm3na.com/303/Sm3na_com_32437.mp3"/>
        </item>
        <item>
            <imag img="https://files.elnashra.com/elnashrafan/pictures/7287731_1463418489.jpg"/>

            <title>سكر زيادة	</title>
            <enclosure url="http://ms4.sm3na.com/303/Sm3na_com_32435.mp3"/>
        </item>
        <item>
            <imag img="https://files.elnashra.com/elnashrafan/pictures/7287731_1463418489.jpg"/>

            <title>تذكر يوم	</title>
            <enclosure url="http://ms4.sm3na.com/303/Sm3na_com_32433.mp3"/>
        </item>
        <item>
            <imag img="https://files.elnashra.com/elnashrafan/pictures/7287731_1463418489.jpg"/>

            <title>رغبة مني	</title>
            <enclosure url="http://ms4.sm3na.com/303/Sm3na_com_32434.mp3"/>
        </item>
        <item>
            <imag img="https://files.elnashra.com/elnashrafan/pictures/7287731_1463418489.jpg"/>

            <title>بكل شي تكذب	</title>
            <enclosure url="http://ms4.sm3na.com/303/Sm3na_com_32432.mp3"/>
        </item>
        <item>
            <imag img="https://files.elnashra.com/elnashrafan/pictures/7287731_1463418489.jpg"/>

            <title>ادري</title>
            <enclosure url="http://ms4.sm3na.com/303/Sm3na_com_32430.mp3"/>
        </item>
        <item>
            <imag img="https://files.elnashra.com/elnashrafan/pictures/7287731_1463418489.jpg"/>

            <title>انا انسانة	</title>
            <enclosure url="http://ms4.sm3na.com/303/Sm3na_com_32431.mp3"/>
        </item>
        <item>
            <imag img="https://files.elnashra.com/elnashrafan/pictures/7287731_1463418489.jpg"/>

            <title>حب كبير	</title>
            <enclosure url="http://ms4.sm3na.com/303/Sm3na_com_9991.mp3"/>
        </item>
        <item>
            <imag img="https://files.elnashra.com/elnashrafan/pictures/7287731_1463418489.jpg"/>

            <title>الف زيك	</title>
            <enclosure url="http://ms4.sm3na.com/303/Sm3na_com_9992.mp3"/>
        </item>
        <item>
            <imag img="https://files.elnashra.com/elnashrafan/pictures/7287731_1463418489.jpg"/>

            <title>ايام</title>
            <enclosure url="http://ms4.sm3na.com/303/Sm3na_com_9993.mp3"/>
        </item>
        <item>
            <imag img="https://files.elnashra.com/elnashrafan/pictures/7287731_1463418489.jpg"/>

            <title>بلا عشق	</title>
            <enclosure url="http://ms4.sm3na.com/303/Sm3na_com_9994.mp3"/>
        </item>
        <item>
            <imag img="https://files.elnashra.com/elnashrafan/pictures/7287731_1463418489.jpg"/>

            <title>لما تتطلع	</title>
            <enclosure url="http://ms4.sm3na.com/303/Sm3na_com_9995.mp3"/>
        </item>
        <item>
            <imag img="https://files.elnashra.com/elnashrafan/pictures/7287731_1463418489.jpg"/>

            <title>لو بس بصلى	</title>
            <enclosure url="http://ms4.sm3na.com/303/Sm3na_com_9996.mp3"/>
        </item>
        <item>
            <imag img="https://files.elnashra.com/elnashrafan/pictures/7287731_1463418489.jpg"/>

            <title>نستنى زمان	</title>
            <enclosure url="http://ms4.sm3na.com/303/Sm3na_com_9997.mp3"/>
        </item>
        <item>
            <imag img="https://files.elnashra.com/elnashrafan/pictures/7287731_1463418489.jpg"/>

            <title>توصى فيا	</title>
            <enclosure url="http://ms4.sm3na.com/303/Sm3na_com_9998.mp3"/>
        </item>
        <item>
            <imag img="https://files.elnashra.com/elnashrafan/pictures/7287731_1463418489.jpg"/>

            <title>وأنا جنبك	</title>
            <enclosure url="http://ms4.sm3na.com/303/Sm3na_com_9999.mp3"/>
        </item>
        <item>
            <imag img="https://files.elnashra.com/elnashrafan/pictures/7287731_1463418489.jpg"/>

            <title>صدفة - حفله	</title>
            <enclosure url="http://ms4.sm3na.com/303/Sm3na_com_22327.mp3"/>
        </item>
        <item>
            <imag img="https://files.elnashra.com/elnashrafan/pictures/7287731_1463418489.jpg"/>

            <title>خدني معك + فضل	</title>
            <enclosure url="http://ms4.sm3na.com/303/Sm3na_com_23812.mp3"/>
        </item>
        <item>
            <imag img="https://files.elnashra.com/elnashrafan/pictures/7287731_1463418489.jpg"/>

            <title>بتلف الدنيا	</title>
            <enclosure url="http://ms4.sm3na.com/303/Sm3na_com_24169.mp3"/>
        </item>
        <item>
            <imag img="https://files.elnashra.com/elnashrafan/pictures/7287731_1463418489.jpg"/>

            <title>حاول مره	</title>
            <enclosure url="http://ms4.sm3na.com/303/Sm3na_com_33262.mp3"/>
        </item>
        <item>
            <imag img="https://files.elnashra.com/elnashrafan/pictures/7287731_1463418489.jpg"/>

            <title>عم غني	</title>
            <enclosure url="http://ms4.sm3na.com/303/Sm3na_com_44886.mp3"/>
        </item>
        <item>
            <imag img="https://files.elnashra.com/elnashrafan/pictures/7287731_1463418489.jpg"/>

            <title>اه منك يا هوا	</title>
            <enclosure url="http://ms4.sm3na.com/303/Sm3na_com_44887.mp3"/>
        </item>
        <item>
            <imag img="https://files.elnashra.com/elnashrafan/pictures/7287731_1463418489.jpg"/>

            <title>يا عايش بعيوني	</title>
            <enclosure url="http://ms4.sm3na.com/303/Sm3na_com_44888.mp3"/>
        </item>
        <item>
            <imag img="https://files.elnashra.com/elnashrafan/pictures/7287731_1463418489.jpg"/>

            <title>بتحب ما بتحب	</title>
            <enclosure url="http://ms4.sm3na.com/303/Sm3na_com_44889.mp3"/>
        </item>
        <item>
            <imag img="https://files.elnashra.com/elnashrafan/pictures/7287731_1463418489.jpg"/>

            <title>بتروح	</title>
            <enclosure url="http://ms4.sm3na.com/303/Sm3na_com_44890.mp3"/>
        </item>
        <item>
            <imag img="https://files.elnashra.com/elnashrafan/pictures/7287731_1463418489.jpg"/>

            <title>بيت حبيبي	</title>
            <enclosure url="http://ms4.sm3na.com/303/Sm3na_com_44891.mp3"/>
        </item>
        <item>
            <imag img="https://files.elnashra.com/elnashrafan/pictures/7287731_1463418489.jpg"/>

            <title>هيدا هيدا	</title>
            <enclosure url="http://ms4.sm3na.com/303/Sm3na_com_44892.mp3"/>
        </item>
        <item>
            <imag img="https://files.elnashra.com/elnashrafan/pictures/7287731_1463418489.jpg"/>

            <title>ما بعرف	</title>
            <enclosure url="http://ms4.sm3na.com/303/Sm3na_com_44893.mp3"/>
        </item>
        <item>
            <imag img="https://files.elnashra.com/elnashrafan/pictures/7287731_1463418489.jpg"/>

            <title>مغروم	</title>
            <enclosure url="http://ms4.sm3na.com/303/Sm3na_com_44895.mp3"/>
        </item>
        <item>
            <imag img="https://files.elnashra.com/elnashrafan/pictures/7287731_1463418489.jpg"/>

            <title>قول شو بدك مني	</title>
            <enclosure url="http://ms4.sm3na.com/303/Sm3na_com_44895.mp3"/>
        </item>
        <item>
            <imag img="https://files.elnashra.com/elnashrafan/pictures/7287731_1463418489.jpg"/>

            <title>ياريت بقدر	</title>
            <enclosure url="http://ms4.sm3na.com/303/Sm3na_com_44896.mp3"/>
        </item>
        <item>
            <imag img="https://files.elnashra.com/elnashrafan/pictures/7287731_1463418489.jpg"/>

            <title>خلوني معو	</title>
            <enclosure url="http://ss1.sm3na.com/201606-mp/Sm3na_com_45862.mp3"/>
        </item>
        <item>
            <imag img="https://files.elnashra.com/elnashrafan/pictures/7287731_1463418489.jpg"/>

            <title>انا انا	</title>
            <enclosure url="http://ms4.sm3na.com/303/Sm3na_com_46253.mp3"/>
        </item>
    </channel>
</rss>
